package three

import java.lang.Exception

interface Callback {
    fun onSuccess(result:Boolean)
}